baseurl: https://example.com
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: 平遙話


languages:
    zh-tw:
        languageName: 傳統漢字
        title: 平陶方言志
        description: 説説平遙話
        weight: 1
        params:
          sidebar:
            subtitle: 説説平遙話
            avatar:
              enabled: true
              local: true
              src: img/avatar.png
    zh-cn:
        languageName: 简化汉字
        title: 平陶方言志
        description: 说说平遥话
        weight: 2
        params:
          sidebar:
            subtitle: 说说平遥话
            avatar:
              enabled: true
              local: true
              src: img/avatar.png

DefaultContentLanguage: zh-tw
hasCJKLanguage: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2023
        customText: Pieng-Yo-Hua

    dateFormat:
        published: 2006-01-02
        lastUpdated: 2006-01-02 15:04 MST

    sidebar:
        emoji: 
        subtitle: 
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc
    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto
    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/CaiJimmy/hugo-theme-stack
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com
          params:
              icon: brand-twitter
related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200
markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4